global:
  identity:
    auth:
      # Disable the Identity authentication for local development
      # it will fall back to basic-auth: demo/demo as default user
      enabled: false

# Disable identity as part of the Camunda core
identity:
  enabled: false

# Disable keycloak
identityKeycloak:
  enabled: false

optimize:
  enabled: false


# Override readiness probe settings
readinessProbe:
  enabled: true
  scheme: HTTP
  probePath: /health/readiness
  initialDelaySeconds: 40  # Allows more startup time
  periodSeconds: 20        # Faster readiness checks
  successThreshold: 1
  failureThreshold: 6      # Higher tolerance for startup issues
  timeoutSeconds: 5        # Longer timeout to avoid transient failures


# Override liveness probe settings
livenessProbe:
  enabled: true            # Enabled to restart stuck containers
  scheme: HTTP
  probePath: /health/liveness
  initialDelaySeconds: 60  # Starts after initial readiness check
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 3      # Quicker recovery from liveness issues
  timeoutSeconds: 5        # Increased to handle slow responses


# Reduce for Zeebe and Gateway the configured replicas and with that the required resources
# to get it running locally
zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 1Gi
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "1"
      memory: "4Gi"

elasticsearch:
  master:
    replicaCount: 1
    # Request smaller persistent volumes.
    persistence:
      size: 1Gi
    resources:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "1"
        memory: "4Gi"

zeebeGateway:
  replicas: 1
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"

connectors:
  enabled: true
  inbound:
    mode: disabled
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"

tasklist:
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"

operate:
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"
