#
# Camunda - v8.4
# https://docs.camunda.io/docs/reference/announcements/#camunda-84
#

global:
  # https://hub.docker.com/u/camunda
  image:
    tag:

console:
  # Camunda Enterprise repository.
  # registry.camunda.cloud/console
  image:
    # renovate: datasource=docker depName=camunda/console lookupName=registry.camunda.cloud/console/console-sm
    tag: 8.4.60

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags?page=&page_size=&ordering=&name=8.4
  image:
    repository: camunda/connectors-bundle
    tag: 8.4.14

operate:
  # https://hub.docker.com/r/camunda/operate/tags?page=&page_size=&ordering=&name=8.4
  image:
    tag: 8.4.10

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags?page=&page_size=&ordering=&name=8.4
  image:
    repository: camunda/optimize
    tag: 8.4.10

tasklist:
  # https://hub.docker.com/r/camunda/tasklist/tags?page=&page_size=&ordering=&name=8.4
  image:
    tag: 8.4.8

webModeler:
  # Camunda Enterprise repository.
  # registry.camunda.cloud/web-modeler-ee
  image:
    # renovate: datasource=docker depName=camunda/web-modeler lookupName=registry.camunda.cloud/web-modeler-ee/modeler-restapi
    tag: 8.4.11

zeebe:
  # https://hub.docker.com/r/camunda/zeebe/tags?page=&page_size=&ordering=&name=8.4
  image:
    tag: 8.4.9

zeebe-gateway:
  # https://hub.docker.com/r/camunda/zeebe/tags?page=&page_size=&ordering=&name=8.4
  image:
    tag: 8.4.9

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: 8.4.14
  keycloak:
    # https://hub.docker.com/r/bitnami/keycloak/tags
    image:
      repository: bitnami/keycloak
      tag: 22.0.5
    postgresql:
      # https://hub.docker.com/r/bitnami/postgresql/tags
      image:
        repository: bitnami/postgresql
        tag: 15.9.0-debian-12-r0

#
# Elasticsearch
#

elasticsearch:
  # https://hub.docker.com/r/bitnami/elasticsearch/tags
  image:
    repository: bitnami/elasticsearch
    tag: 8.16.1
